# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'liverpool' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for liverpool
  pod 'Alamofire', '~> 4.5'
  pod 'lottie-ios'
  
  target 'liverpoolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'liverpoolUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
